name: Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Tag for release.
        required: true
      releaseBranch:
        description: Limit pull requests to the release branch.
        required: true
      sinceTag:
        description: Changelog will start after specified tag.
        required: true

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ github.event.inputs.since }}
          releaseBranch: ${{ github.event.inputs.releaseBranch }}
      - name: Draft Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          name: ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.version }}
          commitish: ${{ github.event.inputs.releaseBranch }}
          body: ${{ steps.changelog.outputs.changelog }}
