# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: ["published"]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          always-auth: true
      - run: npm i -g yarn
      - run: echo ${{ github.event.tag_name }}
      - run: yarn install
      - run: yarn ci
      - run: yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
      - shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.GithubPackgesToken }}
        run: yarn config set npmAuthToken "$env:SUPER_SECRET"
      - run: yarn version -i 0.0.0-${{ github.sha }}
      - run: yarn npm publish
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.GithubPackgesToken }}
